### ISSUE TITLE
troubleshoot help

### ISSUE THREAD

**Issue by Squirre17** [garyttierney/intellij-ghidra#31]
I'm a java newbie, the following is my build error message:
```shell
gradle buildPlugin

> Configure project :
[gradle-intellij-plugin :intellij-ghidra] Gradle IntelliJ Plugin is outdated: 1.10.0. Update `org.jetbrains.intellij` to: 1.15.0
[gradle-intellij-plugin :intellij-ghidra] Error when resolving dependency: DefaultExternalModuleDependency{group='com.jetbrains.intellij.idea', name='ideaIC', version='2023.1', configuration='default'}
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':detachedConfiguration3'.
········
········
········
········
········
        at org.gradle.internal.resource.transfer.AccessorBackedExternalResource.lambda$withContentIfPresent$2(AccessorBackedExternalResource.java:101)
        at org.gradle.internal.resource.transfer.ProgressLoggingExternalResourceAccessor$DownloadOperation.lambda$call$0(ProgressLoggingExternalResourceAccessor.java:125)
        at org.gradle.internal.resource.transfer.AbstractExternalResourceAccessor.withContent(AbstractExternalResourceAccessor.java:39)
        ... 253 more

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':prepareSandbox'.
> Failed to query the value of task ':prepareSandbox' property 'librariesToIgnore'.
   > Failed to query the value of task ':setupDependencies' property 'idea'.
      > Could not resolve all files for configuration ':detachedConfiguration3'.
         > Could not download ideaIC-2023.1.zip (com.jetbrains.intellij.idea:ideaIC:2023.1)
            > Could not get resource 'https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/2023.1/ideaIC-2023.1.zip'.
               > Premature end of Content-Length delimited message body (expected: 754,488,038; received: 198,975,577)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

seems like it can't parse `gradle.properties` properly.
my env:
```
java --version
java 11.0.19 2023-04-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.19+9-LTS-224)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.19+9-LTS-224, mixed mode)

intellij : 2023.1

gradle --version

------------------------------------------------------------
Gradle 7.4
------------------------------------------------------------

Build time:   2022-02-08 09:58:38 UTC
Revision:     f0d9291c04b90b59445041eaa75b2ee744162586

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.19 (Oracle Corporation 11.0.19+9-LTS-224)
OS:           Windows 11 10.0 amd64
```

my `gradle.properties` :
```
# IntelliJ Platform Artifacts Repositories
# -> https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html

pluginGroup = com.codingmates.ghidra
pluginName = IntelliJ Ghidra
pluginVersion = 0.4.1

# See https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
# for insight into build numbers and IntelliJ Platform versions.
pluginSinceBuild = 231
pluginUntilBuild = 231.*

# IntelliJ Platform Properties -> https://github.com/JetBrains/gradle-intellij-plugin#intellij-platform-properties
platformType = IC
platformVersion = 2023.1

# Plugin Dependencies -> https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html
# Example: platformPlugins = com.intellij.java, com.jetbrains.php:203.4449.22
platformPlugins = com.intellij.java

# Java language level used to compile sources and to generate the files for - Java 11 is required since 2020.3
javaVersion = 11

# Gradle Releases -> https://github.com/gradle/gradle/releases
gradleVersion = 7.4

```

I dont know what I did wrong.😢

**Comment by garyttierney** [comment]
It looks like you hit a network error (either on your side or JetBrains) during the download of the IntelliJ binaries. If you remove the `build` folder and try again you might have more success.
