### ISSUE TITLE
2024.2.1 Support

### ISSUE THREAD

**Issue by fmagin** [garyttierney/intellij-ghidra#40]
**Describe the bug:**
No release available for 2024.2.1 which was released at the end of August.

I'm not sure if there are any breaking API changes in the new version and the plugin needs to be adapted, or some build process just has to be re-triggered and published.

I'm working around it for now by just downgrading Intellij back to `2024.1.6`, and assuming that it just needs to be rebuilt and published to the JetBrains marketplace.

**Comment by v-p-b** [comment]
I updated gradle.properties so the version matcher will allow the plugin to be loaded into the latest IDEA (2024.2.3).

```diff
-pluginUntilBuild = 241.*
+pluginUntilBuild = 242.*
```

The plugin loads fine and Ghidra (11.2) launches, but when I try to open a Program from the Project Manager I get a large number of Sleigh related errors:

```
Error creating verifier
ghidra.app.plugin.processors.sleigh.SleighException: Error creating verifier
	at ghidra.app.plugin.processors.sleigh.SleighLanguageValidator.validateSleighFile(SleighLanguageValidator.java:210)
[...]
```

This doesn't happen when I open the same Program outside IDEA.

**Comment by fmagin** [comment]
That's definitely weird. I only need the plugin for automatically associating the source files, and I have my own run config to start Ghidra that still works with 11.2

```
$ cat .idea/runConfigurations/Run_Ghidra.xml
<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="Run Ghidra" type="Application" factoryName="Application">
    <option name="ALTERNATIVE_JRE_PATH" value="21" />
    <option name="ALTERNATIVE_JRE_PATH_ENABLED" value="true" />
    <option name="MAIN_CLASS_NAME" value="ghidra.GhidraLauncher" />
    <module name="reai-ghidra.main" />
    <option name="PROGRAM_PARAMETERS" value="ghidra.GhidraRun" />
    <option name="VM_PARAMETERS" value="-Djava.system.class.loader=ghidra.GhidraClassLoader -Dfile.encoding=UTF8 -Duser.country=US -Duser.language=en -Duser.variant= -Dsun.java2d.opengl=false -Djdk.tls.client.protocols=TLSv1.2,TLSv1.3 -Dcpu.core.limit= -Dcpu.core.override= -Dfont.size.override= -Dpython.console.encoding=UTF-8 -Xshare:off -Dsun.java2d.pmoffscreen=false -Dsun.java2d.xrender=true -Dsun.java2d.uiScale=1 -Dawt.useSystemAAFontSettings=on" />
    <method v="2">
      <option name="Make" enabled="true" />
    </method>
  </configuration>
</component>⏎   
```

**Comment by v-p-b** [comment]
Thanks for the quick feedback! To clarify, I used intellij-ghidra to create the Run Configuration as described in the README. Now I tried manually adding the config you provided (I guess it's based on [this post](https://reversing.technology/2019/11/18/ghidra-dev-pt3-dbg.html)?) with the following results:
* Ghidra couldn't find an `application.properties` file, fo I added my `{GHIDRA_ROOT}\Ghidra` to the classpath. I'm not sure this is the right `application.properties` file, but the launcher seems to accept it.
* Now startup fails with the following exception:
```
NullPointerException - Cannot invoke "java.net.URL.toExternalForm()" because "url" is null (SwingExceptionHandler) java.lang.NullPointerException: Cannot invoke "java.net.URL.toExternalForm()" because "url" is null
	at ghidra.base.help.GhidraHelpService.mapHelpToModule(GhidraHelpService.java:120)
	at ghidra.base.help.GhidraHelpService.findHelpSetsByModule(GhidraHelpService.java:104)
	at ghidra.base.help.GhidraHelpService.loadHelpSets(GhidraHelpService.java:85)
	at ghidra.base.help.GhidraHelpService.<init>(GhidraHelpService.java:60)
	at ghidra.base.help.GhidraHelpService.install(GhidraHelpService.java:51)
	at ghidra.GhidraRun.lambda$launch$1(GhidraRun.java:83)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

I haven't debugged this one yet, but seems like some trivial (yet annoying) issue with the loading of help files. My config now looks like this:

```xml
<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="Run Ghidra" type="Application" factoryName="Application">
    <option name="ALTERNATIVE_JRE_PATH" value="corretto-21" />
    <option name="ALTERNATIVE_JRE_PATH_ENABLED" value="true" />
    <classpathModifications>
      <entry path="/path/to/ghidra_11.2/Ghidra" />
    </classpathModifications>
    <option name="MAIN_CLASS_NAME" value="ghidra.GhidraLauncher" />
    <module name="Base" />
    <option name="PROGRAM_PARAMETERS" value="ghidra.GhidraRun" />
    <option name="VM_PARAMETERS" value="-Djava.system.class.loader=ghidra.GhidraClassLoader -Dfile.encoding=UTF8 -Duser.country=US -Duser.language=en -Duser.variant= -Dsun.java2d.opengl=false -Djdk.tls.client.protocols=TLSv1.2,TLSv1.3 -Dcpu.core.limit= -Dcpu.core.override= -Dfont.size.override= -Dpython.console.encoding=UTF-8 -Xshare:off -Dsun.java2d.pmoffscreen=false -Dsun.java2d.xrender=true -Dsun.java2d.uiScale=1 -Dawt.useSystemAAFontSettings=on" />
    <method v="2">
      <option name="Make" enabled="true" />
    </method>
  </configuration>
</component>
```

**Comment by fmagin** [comment]
> I guess it's based on [this post](https://reversing.technology/2019/11/18/ghidra-dev-pt3-dbg.html)?

Somewhat, I think I never wrote a dedicated post for developing/debugging a plugin, which is my main concern nowadays. I have just been copying along those run configs since before I ever wrote these posts.

Are you working with a plugin or a Ghidra source setup? `<module name="Base" />` looks like a Ghidra source setup, I haven't tried those in a while and haven't tried them with 11.2, they might have changed something that breaks that

**Comment by v-p-b** [comment]
> Are you working with a plugin or a Ghidra source setup?

I don't think I follow: I'm developing a simple script and my current goal is to simply launch Ghidra from IDEA so I can eventually debug it. I got the "Base" from the linked post  - as I understand it specifies the module where `GhidraLanucher` resides. My Ghidra installation itself is a release (binary) distribution.

**Comment by fmagin** [comment]
> My Ghidra installation itself is a release (binary) distribution.
Ah, okay, then `Base` is not necessarily correct. That blogpost only discusses how to setup a development setup for the https://github.com/NationalSecurityAgency/ghidra repository (i.e. if you want to create something that will be a PR to Ghidra itself), if you just want to write a plugin there is a simpler setup.

But I think I never actually made it work with _only_ a script, I always had a `build.gradle` file for a full plugin in the IntelliJ project, which then has a block like
```
sourceSets {
	main {
		kotlin {
			srcDirs 'ghidra_scripts'
		}
	}
}
```
in it to add the `ghidra_scripts` folder.

> as I understand it specifies the module where GhidraLanucher resides.

It specifies the entire classpath that IntelliJ will use when starting. It might be enough for just a script, but for plugin development it needs to be the plugin classpath

The run config I posted above is for such a plugin setup, but that one specifies that the classpath of the module `reai-ghidra.main` should be used, which is the plugin I'm currently developing. This should be changed to the plugin one is currently developing, but IntelliJ should just suggest the correct name in the dropdown menu when editing the config.

**Comment by v-p-b** [comment]
> It specifies the entire classpath that IntelliJ will use when starting. [...] that one specifies that the classpath of the module reai-ghidra.main should be used, which is the plugin I'm currently developing. 

Bingo! I obviously misunderstood that setting, but this explanation made much sense, so I set my `<module>` to point to my project and Ghidra now successfully strart from IDEA! Thank you for your help!

I'll keep this issue open as I think the original problem (no release) still stands, and I want to run some additional tests to verify everything works as expected.

**Comment by fmagin** [comment]
We definitely side-tracked this issue, but it's a good reminder that this plugin doesn't really do any magic, it just automates a bunch of things.

The only thing I never managed to properly automate was automatically adding all the `-src.zip` files as sources, so for that alone this IDE Plugin is worth it, but one can manage without it.

Given your confusion and to make sure that this works I set up a GH template repository that should be sufficient to start scripting with IntelliJ: https://github.com/fmagin/ghidra_scripts_project_template
